### ISSUE TITLE
Small UI Fixes

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#109]
There was no padding in the header before:

![Screenshot from 2020-01-25 23-33-30](https://user-images.githubusercontent.com/2096087/73128134-23d08300-3fcb-11ea-84b6-95ac951a53aa.png)

But now it does have it:
![Screenshot from 2020-01-25 23-33-18](https://user-images.githubusercontent.com/2096087/73128136-2af79100-3fcb-11ea-963d-d0b1da4edd73.png)

Nothing changed in the `_index.md` file

```
    height: 155
    paddingX: 50
    paddingY: 0
    align: left
```

**Comment by nisrulz** [comment]
The text moved a bit up and is not in line with the drop icon and the logo

![Screenshot from 2020-01-25 23-35-54](https://user-images.githubusercontent.com/2096087/73128162-7f9b0c00-3fcb-11ea-8da2-9c96867b5f2f.png)

**Comment by zzossig** [comment]
Something changed when I tried to support IE11.
Thanks! Will be fixed

**Comment by nisrulz** [comment]
I meant this actually:

![Screenshot from 2020-01-26 11-13-14](https://user-images.githubusercontent.com/2096087/73133733-12b85e00-402d-11ea-84ff-295a52e93de3.png)
![Screenshot from 2020-01-26 11-14-32](https://user-images.githubusercontent.com/2096087/73133734-1350f480-402d-11ea-84f0-8ccd37d3cb8d.png)


The text is not vertically centered wrt to the height of the logo or drop icon. 

I will look into it and maybe open a PR.

**Comment by zzossig** [comment]
I think the logo text aligned well.
But look like the icon is still mispositioned.
I made some changes. Looks good my end

**Comment by ndgnuh** [comment]
I think the list of posts can use a little padding too. Mine just look like this, with no padding at all:
![zzo](https://user-images.githubusercontent.com/33273948/73160082-a6b42380-411a-11ea-8dce-9929dee4bec7.png)

**Comment by zzossig** [comment]
Did you update the theme latest?

**Comment by ndgnuh** [comment]
> Edit: Did you update the theme latest? I can't reproduce it on my end

I actually updated the theme just before taking that screenshot, let my try updating again...

**Comment by zzossig** [comment]
Can you check the issue on this site?
[https://themes.gohugo.io/theme/hugo-theme-zzo/en](https://themes.gohugo.io/theme/hugo-theme-zzo/en)

Or can you give me some repository that I can take a look at?

**Comment by ndgnuh** [comment]
Weird, the example site looks fine, I'll have to check if I messed something up.

**Comment by zzossig** [comment]
Ah, this is my mistake.
I just found that your blog use summary shape to `card`.
I'll update soon

**Comment by ndgnuh** [comment]
![image](https://user-images.githubusercontent.com/33273948/73167121-d9b1e380-4129-11ea-96ea-d885e3a4af6f.png)

Works perfectly. Thank you!

**Comment by ndgnuh** [comment]
I want to report a few more problems (with some suggestion). Since this issue is about small UI fixes, I guess I'll put small visual bugs here.

## The date shows up in my list, but not in single pages
![image](https://user-images.githubusercontent.com/33273948/73436056-5e943b80-437c-11ea-9549-48154edcac9c.png)

## Markdown in `notice` shortcodes

I suppose I can put `markdownify` in the `notice` shortcode, but then the element looks weird inside:

- The links are unreadable, i suggest make them bold, underline and have the color of the border minus 16 each color. (*eg*: info border is `#6bb1e0`, we'll use `#5bc1d0` for the links)

![image](https://user-images.githubusercontent.com/33273948/73436891-ecbcf180-437d-11ea-813c-29888a8c4c94.png)

- The tables doesn't have any padding
![image](https://user-images.githubusercontent.com/33273948/73437253-97351480-437e-11ea-9b33-f02c1ea4ad76.png)

- Code elements doesn't really goes with the notice (still, it's readable)
![image](https://user-images.githubusercontent.com/33273948/73437662-57226180-437f-11ea-9d1a-70ff81709a21.png)

- Headers inside notice is possible, but it's weird and impractical to do this, let's just skip this one

**Comment by zzossig** [comment]
Thanks for the issue, I always welcome the UI fixes.
I have some questions.

1. Do you have `i18n` file in your language? In your case, you may need `vi.toml` file in `root/data` folder
![zv](https://user-images.githubusercontent.com/52706977/73438743-de78d080-4391-11ea-8545-522aac985880.png)

2. I don't understand what you mean
    > Code elements doesn't really goes with the notice (still, it's readable)

    How can I do for this?

**Comment by ndgnuh** [comment]
1. I have i18n folder and file for my language, but it's under /root, not /root/data/, I don't have my laptop now, so I'll try it later
2. Sorry, I forgot to include suggestion. Imo the inline codes should have the same background color of the notice, but a little bit darker. Since they don't have highlight, you won't have to worry about readability. I think multiline code fences is fine they way it is, there's no reason to include it in a notice anyway.

**Comment by zzossig** [comment]
Oops I mistyped. Your i18n file should inside the root/i18n folder, not data folder.

Ok I’ll do some work on this

**Comment by zzossig** [comment]
@ndgnuh 
Now we have better notice shortcode thanks for your advice.
And I suspect you might have the wrong configuration regarding `i18n`.
Check the `defaultContentLanguage` value set to your language, check the `languages.toml` file,

**Comment by ndgnuh** [comment]
The date bug was by bad, sorry, I didn't read the example `i18n/en.toml`. But I suggest the README should either: link to the example [`i18n/en.toml`](https://github.com/zzossig/hugo-theme-zzo/blob/master/i18n/en.toml), or suggest users to copy that file then modify in instead of making a new one.

**Comment by zzossig** [comment]
Ok, I’ll add it in the documentation

**Comment by ndgnuh** [comment]
I've ran into some other problems:

1. Inline code have different color when it's on the first paragraph.
2. The white color doesn't look easy to read, maybe using the same text color as the paragraph for inline code block? 

Current:

![image](https://user-images.githubusercontent.com/33273948/73478384-8e693080-43c8-11ea-82d9-239602428757.png)

Suggestion (I changed `code`'s `color` to `inherit`)
![Screenshot_2020-01-31 Issue](https://user-images.githubusercontent.com/33273948/73478794-51516e00-43c9-11ea-8361-ffb99bc58bb7.png)

**Comment by zzossig** [comment]
@ndgnuh Thanks for the suggestion.
I made some changes. I didn't used `inherit` but it works anyway.
And always feel free to open new issue to suggest fixing UI.
I prefer to solve the issue one by one, each of them keeps the small piece and deal with only one subject.

@nisrulz I'm closing this issue because this thread is too long and I think the icon is aligned center now.
