### ISSUE TITLE
feature request: full text search

### ISSUE THREAD

**Issue by WeiMXi** [zzossig/hugo-theme-zzo#140]
zzo is a great theme, and I'm learning how to use it now.
And I notice that your [doc website](https://zzodocs.netlify.com/) seem can use full text search, but hugo theme [zzo](https://themes.gohugo.io//theme/hugo-theme-zzo/en/) can't. zzo only can search the title of text. And if I'm not mistaken, the doc website is also using hugo theme. So I think it's don't diffcult to add the function? If the function has performance requirements, can we make it to be a optional features?

**Comment by zzossig** [comment]
I also realized it now.
The zzo theme and the zdoc theme has the same logic to implement the search feature.
I'm using [Fuse](https://fusejs.io/) for the search, and the library does not search if the text is too long.
But the beginning of the contents(maybe 100 ~ 200 text?) can be searched.

I'm not very familiar with the fuzzy search world.
I considered a few other search libraries. None of them satisfactory.
Maybe, I need to make my own library to meet all the requirements.
I'll consider more about how to better search for this theme.
I'm closing this issue now because it's a very big picture. It maybe not be implemented.
But I will always care about it.
