### ISSUE TITLE
More information about new features

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#148]
Looking in the commits before a submodule with your theme update I occasionally see `[new feature]` commits. It's good that you mark it somehow, but not always given [commit](https://github.com/zzossig/hugo-theme-zzo/commit/7c549e0d5a64a08c165e1c4ecf99374a79ce6071) provides easy to grasp (without code analysis) information about the new feature.

It would be really useful (at least for me :) ) to have new features (or important enhancements) put also somewhere is README with short information what is it, how to use it and date when it was introduced (or a commit where it was "finished" - to be able to check if you have it in your own project).

**Comment by zzossig** [comment]
Yes, I know, I did a poor job on documentation. I'll improve the docs gradually. (but it's still not a very interesting job for me)

Regarding the new features, I'm still not finished the feature completely. I'm still making it.
I'm still talking with the person who first raised the issue. 
Because I need some feedback from the person.
When I think it's done, I'll make the document too.

I think I can close this issue now.
This issue should be dealt with in this page https://github.com/zzossig/zzoDocs/issues 

Anyway, are you going to use the publication page?

**Comment by szpak** [comment]
Thanks for your explanation. I don't plan to use the publication page. The feature I encountered recently was [`[new feature] search result positioning`](https://github.com/zzossig/hugo-theme-zzo/commit/7c549e0d5a64a08c165e1c4ecf99374a79ce6071). I will try to play with it and report my observations.

**Comment by zzossig** [comment]
Just set the `searchResultPosition` parameter
https://github.com/zzossig/hugo-theme-zzo/commit/8de05d62e5bf4cf5baacf6ba20c0ad2fe2818863
