### ISSUE TITLE
How to add sitemap.xml

### ISSUE THREAD

**Issue by fandean** [zzossig/hugo-theme-zzo#234]
I recently learned about sitemap.xml.  Can zzo theme generate sitemap.xml?

**Comment by szpak** [comment]
I follow the instruction found at the [Hugo forum](https://discourse.gohugo.io/t/custom-robots-txt-and-sitemap-xml-templates/11869?u=szpak) and it works fine with Zzo. You might also want to manage `robots.txt` as mentioned in the same article.

**Comment by fandean** [comment]
I customized a sitemap.xml and the end result looks like  [this](https://www.thisfaner.com/sitemap.xml)

**Comment by szpak** [comment]
Nice. One suggestion. In `robots.txt` you have:
> Disallow: /notes/motto/

However, `sitemap.xml` contains:
> https://www.thisfaner.com/notes/motto/motto-010/

and others. It generates confusion. You should exclude them from your `sitemap.xml`.

**Comment by fandean** [comment]
@szpak I want to use the following two methods to filter, but was unsuccessful
```go
{{ range where (where .Site.RegularPages "Section" "!=" "gallery") "Section" "!=" "motto"}}
```
```go
{{ range where (where .Site.RegularPages "Section" "!=" "gallery") "CurrentSection" "!=" "motto"}}
```
What's wrong?

```
notes
|---motto
        |--- _index.md
        |--- motto01.md
```

**Comment by zzossig** [comment]
@fandean
Have you checked what value `(.Site.RegularPages "Section")` has?
So,  you want to exclude the `motto` folder in `sitemap.xml` files, right?
I think `"Section" "!=" "motto"}}` was not successful because the section is defined with the root folder.(in our case, the `notes` is the section name). I don't know why the section name is not changed even though we have `_index.md` file in `motto`.

As hugo document says, https://gohugo.io/content-management/sections/

>By default, all the first-level directories under content/ form their own sections (root sections).
If you need a specific template for a sub-section, you need to adjust either the type or layout in front matter.

So, How about set `type` in your `notes/motto` markdown files and filter it like this
```
{{ range where (where .Site.RegularPages "Section" "!=" "gallery") ".Type" "!=" "motto"}}
```

I think you can get an idea

**Comment by fandean** [comment]
Thank you for your suggestion, I use other ways to filter the motto
