### ISSUE TITLE
Overflow due to too long words in summary

### ISSUE THREAD

**Issue by fandean** [zzossig/hugo-theme-zzo#247]
![Snipaste_2020-04-07_01-26-50](https://user-images.githubusercontent.com/25637720/78587065-02afcc80-786f-11ea-80cf-ce4ec5be00e3.png)

Unable to wrap org.springframework.boot.convert.durationunit in summary, resulting in overflow

**Comment by zzossig** [comment]
I'm using `word-break: break-word;` css syntax for the summary
https://github.com/zzossig/hugo-theme-zzo/blob/ceef3905795b418fee3bdb908f022135411d5314/assets/sass/components/_summary.scss#L12
And this is expected behavior.
I think modern browsers like chrome, firefox interpret `java.time.Duration` as one word.
So, how about add space between word instead of the dot(.) something like this `java time duration`
