### ISSUE TITLE
 favicon-generator setting doesn't work

### ISSUE THREAD

**Issue by couchp95** [zzossig/hugo-theme-zzo#282]
Just followed the steps in the doc:
1. Make favicons from favicon-generator site.
2. Make a folder at root/static/favicon
3. Unzip the generated favicon to that folder.
<img width="866" alt="zzo1" src="https://user-images.githubusercontent.com/16264377/83356556-8ed6ff80-a399-11ea-8b61-4fc21eb4d455.PNG">
4. Set the config param useFaviconGenerator to true
<img width="442" alt="zzo2" src="https://user-images.githubusercontent.com/16264377/83356568-98f8fe00-a399-11ea-9e67-5a382259d74e.PNG">
After hugo ran, the favicon.ico, favicon.png and logo.png in the public folder are still the same from the theme.
<img width="856" alt="zzo3" src="https://user-images.githubusercontent.com/16264377/83356553-8d0d3c00-a399-11ea-8277-4ce9d7545691.PNG">

**Comment by zzossig** [comment]
I think this is expected behavior.
Did you check the website?
The icons in the screenshot are still the same because you didn't override the theme's icon.
You can see the icons in `themes/zzo/static/(favicon.ico, favicon.png, logo.png ....)`.
And your root folder `root/static/` may don't have that favicon image file, right?
So, if you don't want to generate that icon, just override the theme's icon by putting the icons to your root/static folder.
