### ISSUE TITLE
Unable to add custom CSS to website. 

### ISSUE THREAD

**Issue by jmhimara** [zzossig/hugo-theme-zzo#300]
I’m having some trouble adding custom CSS to my hugo website. Following the instructions as specified in the [theme’s documentation](https://zzodocs.netlify.app/docs/customization/customcss/) does not work. My changes are not taking any effect. I even tried the specific example provided there (i.e. change the background color of #body), and that does not work either.

Any suggestions?

Thanks.

PS: I've tried adding the custom.css file in both the assets and static folders, and tried a couple of different variations of the directory structure in the param.toml file, but I'm still unable to get this to work

**Comment by FixFlare** [comment]
The documentation is confusing because it doesn't give a full path to the assets folder. You're left to guess what zzo means by that.

I've got it to work by placing my custom.css inside this folder: 

**ROOT OF YOUR WEBSITE**\themes\zzo\assets\css

This does work, but I'm not sure if it is correct. It also creates issues for me when deploying because the sub module has been modified.

**Comment by zzossig** [comment]
custom CSS works fine.
Follow the below steps.

1. Make a `assets` folder in your root directory (root/assets) not in the themes folder (root/themes/zzo/assets)
2. Add `custom_css` param to `params.toml` file. for example
```toml
...
custom_css = ["css/custom.css"]
...
```
3. Make `css` folder in your assets folder (root/assets/css) because we set the custom CSS path to `css/custom.css` in the step 2
4. Make `custom.css` file in your `root/assets/css` folder. We name it `custom.css` because we set the file name as is in step 2
5. Restart Hugo by typing [hugo server]. Because it will not hot reloaded

**Comment by jmhimara** [comment]
Hi,

I've already tried that, and unfortunately, it does not work. Following exactly the steps above give me the following error when I run `hugo server`:

`Error: Error building site: TOCSS: failed to transform "css/custom.css" (text/css): resource "css/css/custom.css_b95b077eb505d5c0aff8055eaced30ad" not found in file cache`

If I type `custom_css = ["custom.css"] inside the param.toml file (i.e. without the "css/" prefix), then I don't get the error, but the css code in custom.css does not take effect.

Please reopen the issue because it's not resolved for me. 

Thanks.

**Comment by alekc** [comment]
@jmhimara it's now late, but leaving the answer for people who arrives here with google. The error `Error: Error building site: TOCSS: failed to transform "css/custom.css" (text/css): resource "css/css/custom.css_b95b077eb505d5c0aff8055eaced30ad" not found in file cache` is most likely caused by the fact  that you are not running an extended version of hugo.
