### ISSUE TITLE
Search exact word and not letters pattern

### ISSUE THREAD

**Issue by mmiots9** [zzossig/hugo-theme-zzo#409]
Hi, thank you very much for the introduction of the search for the content. 
I still have some trouble: it does not search for the exact word I type, but for all the possible combinations with the letters that I'm writing, even with only part of them. 
E.g. in the image I'm looking for "needed", I know it is a word in a post. First of all it does not find it (I set searchDistance = 1000000000, and that word is at the beginning of the post); moreover, as you can see, it finds combinational patterns of the letters in "needed". 
Thanks for your attention
![Screenshot 2021-04-20 at 10 40 26 AM](https://user-images.githubusercontent.com/67107582/115365947-236e6a00-a1c5-11eb-981e-6574066c35eb.png)

**Comment by zzossig** [comment]
I introduced new param `searchThreshold` for you.
You can set it from `0.0` to`1.0` and `0.0` is for the perfect match.
I tested it to 0.0 and it is not really a perfect match.
I don't know why since I'm using an opensource for the search: `fuse.js`
As for the `searchDistance`, it is also the fuse.js option. 
Hmm, why fuse.js couldn't search your content?(Did you set `searchContent = true`?)
Maybe you set the distance too big? I don't know...

**Comment by mmiots9** [comment]
Thank you very much for the work. 
Unfortunately, it still does not work. It seems it search only in the section that is displayed above the tittle post (e.g. in the previous image, in "introduction to ggplot2" it search from "ggplot2" to "huge num". I tried also with the example site, and the problem remains.
I know it is a lot of work for you, and I don't want to bother you so much. I can suggest to look at Hugo Stack theme which have a functional search engine. Unfortunately I'm not as good to understand the codes below the search engine, maybe you can look at it and try to copy it. 
Have a nice day
