### ISSUE TITLE
Malformed RSS feed URL?

### ISSUE THREAD

**Issue by minukchoi** [zzossig/hugo-theme-zzo#68]
The RSS button URL has an extra forward slash;

https://themes.gohugo.io//theme/hugo-theme-zzo/en//index.xml

and only seems to work on the root domain as the same RSS feed button under any posts returns a  page not found(404);

https://themes.gohugo.io//theme/hugo-theme-zzo/en/posts/math-typesetting//index.xml

I got it to work on my local copy via the following edit in **layouts/partials/footer/links-feed.html** from;

"{{ .Permalink }}/index.xml" 

to 

"{{ .Site.BaseURL }}index.xml" 

and now the RSS button points to the index.xml on the root of the domain.

I wanted to know if this is not the intended behavior?

**Comment by zzossig** [comment]
>The RSS button URL has an extra forward slash

That is the Hugo theme site issue.[https://github.com/gohugoio/hugoThemesSite/issues/72](https://github.com/gohugoio/hugoThemesSite/issues/72)

>and only seems to work on the root domain as the same RSS feed button under any posts returns a page not found(404);

No, not only the home page. It works on every list(section) page. Because Hugo by default makes the RSS on the list page. [https://gohugo.io/templates/output-formats/#default-output-formats](https://gohugo.io/templates/output-formats/#default-output-formats)

As you can see in the link, page(single page)'s default output is only `HTML`. If you need it, tell Hugo that you want to generate the RSS output in the config file(root/config/_default/config.toml). It maybe looks like this.

```toml
...
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"] # add RSS here
...
```

I'm going to close this issue now since the user using this theme needs to do something

**Comment by minukchoi** [comment]
ah, got it - I was using the config file from the exampleSite and it wasn't working there either.

Thanks
