### ISSUE TITLE
Is it possible to add a password to a post?

### ISSUE THREAD

**Issue by dxb22abad** [zzossig/hugo-theme-zzo#87]
zzo really is a great work of art. my blog theme switched to it and never changed again.

Just one more request: 

is it possible to add a password to a post, 'cause sometime we may have troubles sharing things to the public. And a passcode may solve that.

Thanks,

**Comment by zzossig** [comment]
Thank for using this theme!
Actually, I don't understand why the password needs to the post.
We already have the feature to hide post to the public by setting front matter param name `draft`.

For example, in your post markdown file,
```yaml
---
title:
date:
draft: true # I think this is what you are looking for.
...
---

contents
```

Then, the `draft` front matter hides the post to the public.
If you want to see the post in the local environment, start the Hugo by typing
```bash
hugo server -D
```

`-D` flag means show `draft`, otherwise, draft post not showing on.

**Comment by zzossig** [comment]
Sorry, but I don't want to make a `password` because we already have a `draft` feature.

**Comment by dxb22abad** [comment]
Thank you for info about draft.
However, my point is to create some posts that give access only with passcode, instead of shut all viewers out.
anyway, zzo is the best!!

**Comment by WeiMXi** [comment]
@dxb22abad maybe you will like [this](https://github.com/Li4n0/hugo_encryptor), and this is the [demo](http://0n0.fun/post/2019/03/this-is-hugo-encryptor/)
I also think draft is different with encrypt.

**Comment by dxb22abad** [comment]
> @dxb22abad maybe you will like [this](https://github.com/Li4n0/hugo_encryptor), and this is the [demo](http://0n0.fun/post/2019/03/this-is-hugo-encryptor/)
> I also think draft is different with encrypt.

Thanks you, that's great! I agree that encryption differs from drafts. And the password option is more useful when sharing within a  limited range of vewers.
