### ISSUE TITLE
How to open Markdown link in a new tab

### ISSUE THREAD

**Issue by simicn** [zzossig/hugo-theme-zzo#88]
I was wondering how to add target="_blank" to a Markdown link.
I tried like below but it didn't work:
```
[Hugo Host on GitHub](https://gohugo.io/hosting-and-deployment/hosting-on-github/){:target="_blank"}
```

**Comment by zzossig** [comment]
I’ll add this feature soon

**Comment by zzossig** [comment]
I just found that `{:target="_blank"}` is not the part of the Goldmark syntax which is Hugo's markdown rendering library.
So, if you want to use `target=_blank` in Goldmark, You should follow this link
[https://gohugo.io/getting-started/configuration-markup#markdown-render-hooks](https://gohugo.io/getting-started/configuration-markup#markdown-render-hooks)

Or, just use 
```html
<a href="http://..." target="_blank">external link</a>
```
 in the markdown file.

**Comment by simicn** [comment]
> I just found that `{:target="_blank"}` is not the part of the Goldmark syntax which is Hugo's markdown rendering library.
> So, if you want to use `target=_blank` in Goldmark, You should follow this link
> https://gohugo.io/getting-started/configuration-markup#markdown-render-hooks
> 
> Or, just use
> 
> ```
> <a href="http://..." target="_blank">external link</a>
> ```
> 
> in the markdown file.
> 
> Since the markdown render hooks makes all the links to open in a new tab, I'm not going to use it in the theme as default.
> 
> So, just use the `a` tag.

Ok, thanks for your help.

**Comment by sidney-eliot** [comment]
@zzossig It seems like this feature was removed from .md files on github because your example works in this messages but not in .md files.

```
<a href="https://www.google.com" target="_blank">external link</a>
```
<a href="https://www.google.com" target="_blank">external link</a>

Why did someone go out of their way to remove the a tag blank functionality, I think this important to have. It should be added again.

EDIT: 
It seems like github has completely removed this functionality, in the message editor preview the a tag "blank" was working, but as soon as I posted this message the link was no opening a new window.

**Comment by will-s-205** [comment]
@zzossig will you be able to look into issue mentioned above by @Epicrex?
I'm experiencing the same issue. In readme.dm `target="_blank"` doesn't open new tab in browser
Thanks

**Comment by sidney-eliot** [comment]
@will-s-205 GitHub will never support a wide variety of features markdown/ html provides, including this one, for security and uniformity reasons. This is why I completely abandoned GitHub wikis and use quartz instead which deploys my obsidian vault to an Hugo instance running on GitHub pages, alle very easy to setup even for non tec people. (A better reason to why target="_blank" doesn't work is because GitHub wants that every link on their website interacts the same way)

https://github.com/jackyzha0/quartz
