### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by VictorZakharov** [zzossig/hugo-theme-zzo#93]
Is IE11 supported? Seeing lots of weird issues on it - had to fix completely broken stuff via custom css. Still way below Chrome func, no theme switching, no sidebar etc.

**Comment by zzossig** [comment]
I didn’t know that IE user still exist!
I’ll check about it

**Comment by VictorZakharov** [comment]
2-7% of users, depending on which stats you find, doesn't have to be perfect, just "not ugly".
For example - https://www.stetic.com/market-share/browser/
Thanks for checking.

**Comment by nisrulz** [comment]
Worth mentioning, Microsoft released the new Edge browser which runs chromium under the hood i.e it is going to be at par with Chrome browser. 

https://www.microsoft.com/en-us/edge

This issue is still valid, however the market share for IE 11 will only reduce from now on because Microsoft itself is moving away from it.

**Comment by zzossig** [comment]
@VictorZakharov I have tried to support IE11.
Overall UI is fine now in IE11, but there are some limitations.

1. You can not use the gallery in IE11, because I use a library for the gallery and it is not working in IE11. Also, I need async, await syntax for the gallery.

2. I use the `grid` CSS syntax to the layout of the project. It seems that IE11 has a different syntax. So, the sidebar component not positioned to the side, but the bottom.

3. Some component has a different position. (margin, padding, top, left, ...)

**Comment by VictorZakharov** [comment]
@zzossig As long as nothing looks obviously broken, that should be fine.

**Comment by zzossig** [comment]
Did you check the theme on IE11?
Can we close this issue now?

**Comment by VictorZakharov** [comment]
@zzossig  I checked on https://themes.gohugo.io//theme/hugo-theme-zzo/en/
Doesn't look great.
![image](https://user-images.githubusercontent.com/8978766/72990404-14301f00-3dbe-11ea-941c-906180f908f5.png)
And then this big cat picture at the bottom (almost full screen).
Table of contents is completely messed up:
https://themes.gohugo.io//theme/hugo-theme-zzo/en/posts/markdown-syntax/
Theme switcher doesn't work, it just navigates to page top.
Search is broken, doesn't do anything.
Negative margins here (looks broken):
![image](https://user-images.githubusercontent.com/8978766/72990648-886ac280-3dbe-11ea-8678-92022958fa26.png)

**Comment by zzossig** [comment]
No, the theme site not updated. The site update every 3 days.
Check my blog [https://zzossig.io](https://zzossig.io)

**Comment by VictorZakharov** [comment]
On your blog most pages give me 404 (English version):
```
404: NOT_FOUND Code: `RESOURCE_NOT_FOUND` ID: `cle1:zldhs-1579788068534-907ae6272dde`
```
It's difficult for me to navigate Korean, but overall it looks okay.
BTW, regarding grid support, people are using auto-prefixer:
https://medium.com/@elad/supporting-css-grid-in-internet-explorer-b38669e75d66

**Comment by zzossig** [comment]
My blog not supporting English.
I just made the menus with no pages.
I think we can close this issue now.
I'll check the link later! Thank you for the information!

**Comment by zzossig** [comment]
I have quickly tested the Autoprefixer.
It is a good stuff. But it does not generate the right code.
![주석 2020-01-23 233625](https://user-images.githubusercontent.com/52706977/72993755-45016a00-3e39-11ea-95ba-483402c3567b.png)

![주석 2020-01-23 233643](https://user-images.githubusercontent.com/52706977/72993782-50ed2c00-3e39-11ea-9e07-8dc654c1138f.png)

![주석 2020-01-23 233700](https://user-images.githubusercontent.com/52706977/72993783-50ed2c00-3e39-11ea-8457-3c80f6754e73.png)

**Comment by VictorZakharov** [comment]
According to this guy, it will not magically make your existing markup work in IE11, you might need to adjust syntax:
https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/
Quote:
```
Autoprefixer still can’t save you from everything
```

**Comment by zzossig** [comment]
I'll read the post for sure.
I'll dig into it more when I have more time.
Anyway, thanks for the information!
