### ISSUE TITLE
The responsive layout is broken on iPhones

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#99]
![Screenshot from 2020-01-21 00-46-31](https://user-images.githubusercontent.com/2096087/72764245-8c90b780-3be7-11ea-8c5d-b887d5dfa733.png)
![Screenshot from 2020-01-21 00-46-40](https://user-images.githubusercontent.com/2096087/72764246-8c90b780-3be7-11ea-8aa5-b5fb5d71d7ae.png)

**Comment by zzossig** [comment]
It's fixed now.
It happened because I didn't hide the bio component when mobile.
![주석 2020-01-21 111740](https://user-images.githubusercontent.com/52706977/72769961-d1483d00-3c3f-11ea-8ea6-8a67154c943f.png)

**Comment by nisrulz** [comment]
Works :tada:

**Comment by nisrulz** [comment]
Noticed something when I started playing with resizing the screen just now.

![ezgif com-optimize](https://user-images.githubusercontent.com/2096087/72791262-48c59e80-3c37-11ea-9433-c07b8c0aef4e.gif)


The theme changer and the search icon go on top of the title text. 

Also the white space shows up when the screen size is reduced a lot (this one is not as big of a problem because we hardly have these screens now. When you select iphone5 or other phone options in chrome dev tools things are working.)

**Comment by zzossig** [comment]
It seems that some titles in your code might not wrap by the browser.
For example, if we use the title like `zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz`, browser don't wrap it.
So, that's why I did use `break-all` instead of `break-word`.
When we use `break-word` as default, `the user` has to make the title wrappable.

**Comment by nisrulz** [comment]
But it also happens on your blog too. Try it out 🤔 I believe the titles are I have are normal enough? or are they not 🤔

**Comment by zzossig** [comment]
I'm using `display: grid` to make a grid system on the theme.
I set the possible width to `350px ~ 250px` because I don't think more narrow width might not necessary.
![주석 2020-01-21 190012](https://user-images.githubusercontent.com/52706977/72795022-48052a80-3c80-11ea-99f1-088fe8ba1478.png)
![zz](https://user-images.githubusercontent.com/52706977/72795049-52272900-3c80-11ea-8c7e-cac57f5c03a2.png)

**Comment by nisrulz** [comment]
Works for me now. Closing this issue.

**Comment by ndgnuh** [comment]
Excuse me, I'm having the same issue, but I can't seem to fix the responsiveness without either disabling the sidebar or the bio.

Can you share the fix?

**Comment by zzossig** [comment]
Did you use the latest version?
541bbd576d1c228a8adfbe795416166edf7013fe

**Comment by ndgnuh** [comment]
Woops, I didn't realize this issue was 2 days old. I updated to the new version and it worked. Thank you and sorry for the fuzz
